config/routes.rb
SimpleApp::Application.routes.draw do

  root to: 'federations#index'
  resources :federations, except: [:destroy] do
    resources :teams, except: [:index, :destroy]
  end

  resources :seasons, only: [:index, :show]
  resources :leagues, only: [:show]
  resources :cups, only: [:show]
  resources :matchdays, only: [:show] do
    member do
      get :perform
    end
    resource :draw, only: [:show] do
      get :perform
    end
  end

end

app/models/federation.rb
class Federation < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :seasons
  has_many :teams, dependent: :destroy
  has_many :competitions
  # has_many :appointments, through: :competitions
  has_many :cups
  has_many :relegations
  has_many :leagues

  has_one :competition_plan

  validates :name, uniqueness: true


end

app/controllers/federations_controller.rb
class FederationsController < ApplicationController

  before_action :load_federation, only: [:show, :edit, :update, :delete]

  def index
    @federations = Federation.all
  end

  def show
  end

  def new
    @federation = Federation.new
  end

  def create
    @federation = Federation.new(federation_params)
    if @federation.save
      render :show
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @federation.update_attributes(federation_params)
      render :show
    else
      render :edit
    end
  end

  private

  def load_federation
    @federation = Federation.find(params[:id])
  end

  def federation_params
    params.require(:federation).permit(:name)
  end

end

app/views/federations/_federation.html.haml
%ul
  %li
    = link_to federation.name, federation_path(federation)

app/views/federations/_form.html.haml
= simple_form_for federation do |f|
  = f.input :name
  .primary_button
    = link_to "Cancel", federations_path, class: "btn btn-link"
    = f.submit "Speichern", class: 'btn btn-primary'

app/views/federations/edit.html.haml
%h1= "Ändern Verband"
= render partial: 'form', locals: {federation: @federation}

app/views/federations/index.html.haml
%h1= 'Verbände'

= render partial: 'federation', collection: @federations
= link_to "Neuer Verband", new_federation_path, class: 'btn'

app/views/federations/new.html.haml
%h1= "Erstelle Verband"
= render partial: "form", locals: {federation: @federation}

app/views/federations/show.html.haml
%h1= @federation.name
.row
  .span6
    = link_to "Übersicht", federations_path
    = link_to "Ändern", edit_federation_path(@federation), class: 'btn btn-primary'
%hr
.row
  .span2
    = link_to "Neuer Verein", new_federation_team_path(@federation), class: "btn"
%br
%ul
  = render partial: 'teams/team', collection: @federation.teams.order(:name)