config/routes.rb
SimpleApp::Application.routes.draw do

  root to: 'federations#index'
  resources :federations, except: [:destroy] do
    resources :teams, except: [:index, :destroy]
  end

  resources :seasons, only: [:index, :show]
  resources :leagues, only: [:show]
  resources :cups, only: [:show]
  resources :matchdays, only: [:show] do
    member do
      get :perform
    end
    resource :draw, only: [:show] do
      get :perform
    end
  end

end

app/models/matchday.rb
# coding: utf-8

class Matchday < ActiveRecord::Base

  belongs_to :competition
  has_many :games, dependent: :destroy
  has_many :appointments, through: :games
  has_one :season, through: :competition
  has_one :draw # optional - cup matchdays only

  scope :unfinished,
    -> { joins(:games).where("games.finished = FALSE") }

  validates :number,
    uniqueness: { scope: :competition_id },
    presence: true, numericality: true
  validates :start,
    presence: true
  validates :competition,
    presence: true

  # def next_appointable
  #   next_appointment.try(:appointable)
  # end

  # def next_appointment
  #   @appointment ||= appointments.
  #     order(appointed_at: :asc).
  #     first
  # end

  # def current_date_time
  #   next_appointment.
  #     try(:appointed_at) ||
  #   games.
  #     order(performed_at: :desc, second: :desc).
  #     first.try(:current_date_time) ||
  #   start
  # end

  def perform!
    # TODO: find a better way to perform a matchday...:-)
    # next_appointable.perform!
  end

  def has_games?
    games.any?
  end

  def finished?
    has_games? && games.not_finished.empty?
  end

  def can_be_performed?
    !finished?
  end

  def can_be_drawed?
    draw && draw.can_be_performed?
  end

  def previous
    competition.matchdays.find_by(number: number-1)
  end

  def unfinished_previous_matchdays?
    previous_matchdays.unfinished.any?
  end

  def has_board?
    competition.respond_to? :board
  end

  private

  def previous_matchdays
    competition.matchdays.where("matchdays.number < ?", number)
  end

end

app/controllers/matchdays_controller.rb
class MatchdaysController < ApplicationController
  protect_from_forgery except: :perform

  before_action :load_matchday

  def show
  end

  def perform
    @matchday.perform!
    UpdatePlayerStrength.after_matchday(@matchday)
    respond_to do |format|
      format.html { render :show }
      format.js { render partial: 'matchdays/perform' }
    end
  end

  private

  def load_matchday
    @matchday = Matchday.find(params[:id])
  end
end

app/views/matchdays/_game.html.haml
%tr
  %td= game.home.name
  %td= game.guest.name
  %td
    - if game.home_half_goals
      = "(#{game.home_half_goals}:#{game.guest_half_goals})" 
    - else
      = "-"
  - if game.home_full_goals
    %td
      ="(#{game.home_full_goals}:#{game.guest_full_goals})"
  - if game.home_xtra_full_goals
    %td
      ="(#{game.home_xtra_full_goals}:#{game.guest_xtra_full_goals})"
  %td
    - if game.started?
      = "#{game.home_goals} : #{game.guest_goals}" 
    - else
      = "-"

app/views/matchdays/_perform.js.haml
$("#games").replaceWith("#{escape_javascript(render partial: "game", collection: @matchday.games)}");
- sleep 0.18
$(".perform").replaceWith("#{escape_javascript(link_to "Stop", matchday_path(@matchday),id: "Stop", class: "btn", method: :get)}");
document.getElementById('Step').click();

app/views/matchdays/_run.html.haml
#games
  %h2
    = "#{@matchday.current_date_time.time}"
  .col-md-6
    %table.table-condensed.table-bordered
      = render partial: 'game', collection: @matchday.games.ordered
    - if @matchday.can_be_performed?
      .perform
        = link_to "Start", perform_matchday_path(@matchday), remote: true, class: "btn"
      = link_to "", perform_matchday_path(@matchday), remote: true, class: "btn", id: "Step"
  .col-md-6
    - if @matchday.has_board?
      = render partial: "leagues/board", locals: {league: @matchday.competition}

app/views/matchdays/show.html.haml
#matchday
  - if @matchday.can_be_drawed?
    = render partial: "matchdays/draws/draw", locals: {draw: @matchday.draw}
  -else
    %h1
      = "#{@matchday.competition.name} #{@matchday.competition.season.year} - #{@matchday.number}. Spieltag"
    - if @matchday.has_games?
      = render "run"
    - else
      %h2
        = "#{@matchday.current_date_time.time}"
      Keine Spiele verfügbar